---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections: 
upload_dir: portfolio/.vuepress/public/upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: portfolio/.vuepress/dist
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: npm run site:develop
  publish_command: npm run site:build
  output_directory: portfolio/.vuepress/dist
  preview_command: npm run site:build
