name: Deploy / Test
on:
  push:
    branches:    
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build

      - name: Deploy to Netlify
        id: deploy
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          VUE_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.VUE_APP_CONTENTFUL_ACCESS_TOKEN }}
          VUE_APP_CONTENTFUL_SPACE_ID: ${{ secrets.VUE_APP_CONTENTFUL_SPACE_ID }}
  test:
    name: 'Test'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test
      env:
        # This might depend on your test-runner/language binding
        PLAYWRIGHT_TEST_BASE_URL: ${{ steps.deploy.outputs.deploy-url }}
